name: Screen Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome97-ff96
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1

      - name: Test
        uses: cypress-io/github-action@v1

      - name: Store screenshots
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: cypress/screenshots
