name: Screen Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1

      - name: Test
        continue-on-error: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        uses: cypress-io/github-action@v1
        with:
          # to run component tests we need to use "test-visual" command
          command: yarn test-visual

      - name: Store screenshots
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: cypress/screenshots

      - name: Fail if diff found
        run: test -n "$(find ./cypress -type d -name "__diff_output__")"
